language: c++
dist: bionic
before_install:
 - sudo apt-get install -y openjdk-11-jdk
 - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
 - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
 - sudo apt-get update
 - sudo apt-get install bazel
addons:
  apt:
    update: true
install: bazel test //... --test_output=all
compiler: gcc